/// BstocK App Custom Icons
/// Font generated by FlutterIcon.com from custom SVG assets.
/// Contains the BstocK logo and AshReef Labs logo icons.

import 'package:flutter/widgets.dart';

/// Unified icon class for app-wide brand icons.
/// 
/// Usage:
///   Icon(AppIcons.bstock, size: 24, color: Colors.blue)
///   Icon(AppIcons.ashreef, size: 16, color: Colors.grey)
class AppIcons {
  AppIcons._();

  static const String _fontFamily = 'MyFlutterApp';

  /// BstocK logo icon (the M/V mark)
  static const IconData bstock = IconData(
    0xe800,
    fontFamily: _fontFamily,
  );

  /// AshReef Labs logo icon
  static const IconData ashreef = IconData(
    0xe802,
    fontFamily: _fontFamily,
  );
}

/// Legacy class name for backwards compatibility.
/// @deprecated Use [AppIcons] instead.
class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  @Deprecated('Use AppIcons.bstock instead')
  static const IconData bstock_font =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  
  @Deprecated('Use AppIcons.ashreef instead')
  static const IconData ashreef_logo =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
